[package]
name = "py-hftbacktest"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module"] }
hftbacktest = { path = "../rust", features = ["backtest"] }

[lib]
name = "py_hftbacktest"
crate-type = ["cdylib"]